[2024-11-18T03:48:09.068+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: create_test_dir.make_directory manual__2024-11-18T03:48:08.471177+00:00 [queued]>
[2024-11-18T03:48:09.076+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: create_test_dir.make_directory manual__2024-11-18T03:48:08.471177+00:00 [queued]>
[2024-11-18T03:48:09.077+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-11-18T03:48:09.093+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): make_directory> on 2024-11-18 03:48:08.471177+00:00
[2024-11-18T03:48:09.100+0000] {standard_task_runner.py:60} INFO - Started process 11643 to run task
[2024-11-18T03:48:09.104+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'create_test_dir', 'make_directory', 'manual__2024-11-18T03:48:08.471177+00:00', '--job-id', '3551', '--raw', '--subdir', 'DAGS_FOLDER/directory.py', '--cfg-path', '/tmp/tmph3944lvn']
[2024-11-18T03:48:09.106+0000] {standard_task_runner.py:88} INFO - Job 3551: Subtask make_directory
[2024-11-18T03:48:09.160+0000] {task_command.py:423} INFO - Running <TaskInstance: create_test_dir.make_directory manual__2024-11-18T03:48:08.471177+00:00 [running]> on host 3c704ad499e6
[2024-11-18T03:48:09.239+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='create_test_dir' AIRFLOW_CTX_TASK_ID='make_directory' AIRFLOW_CTX_EXECUTION_DATE='2024-11-18T03:48:08.471177+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-18T03:48:08.471177+00:00'
[2024-11-18T03:48:09.241+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-18T03:48:09.241+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'mkdir -f /opt/***/dags/output/test_dir']
[2024-11-18T03:48:09.252+0000] {subprocess.py:86} INFO - Output:
[2024-11-18T03:48:09.256+0000] {subprocess.py:93} INFO - mkdir: invalid option -- 'f'
[2024-11-18T03:48:09.256+0000] {subprocess.py:93} INFO - Try 'mkdir --help' for more information.
[2024-11-18T03:48:09.257+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-11-18T03:48:09.267+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-11-18T03:48:09.270+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=create_test_dir, task_id=make_directory, execution_date=20241118T034808, start_date=20241118T034809, end_date=20241118T034809
[2024-11-18T03:48:09.282+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 3551 for task make_directory (Bash command failed. The command returned a non-zero exit code 1.; 11643)
[2024-11-18T03:48:09.316+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-11-18T03:48:09.340+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
